Rework of the TMB calculation module
cio-abcd/variantinterpretation pull request #56
Opened 2024-12-03 15:20 UTC by biolancer

This PR reworks the TMB module and BED preprocessing, ensuring compatibility with multi VCF files and allows a better finetuning of the TMB calculation procedure. It furthermore fixes the missingbgzip-compression in `VCFPROC` and minor typos in the `create_vembrane_fields.py`.

Main features:
- Added Multi-VCF support, generating separate reports for tumor-normal pairs.
- Added `--prefilter_tmb` as option which limits TMB calculation to the regions covered in the provided BED file
- Added `--consequence_tmb` as option taking a single line comma separated file to prefilter mutations from the TSV reports. To ensure that no mutations are lost if the flag is not set, a template file containing all [VEP consequences](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html) was created and saved under `assets/`, which is also linked as default file should the flag not be set.
- BED file processing was restructured in the `process_bedfile.py` script. The new script allows BED files with additional columns to be provided and to be used for other processes (e.g. additional annotation using `bcftools annotate`) while minimizing the BED file for later downstream processes.

Potential caveats:
- Currently, the allowed chromosomes which are parsed and checked in `CHECKBEDFILE` are hard-coded. This could pose problems if the reference genome is changed from GRCh37/GRCh38.
- While the new TMB calculation is working as intended in my testing runs, small differences in the initial amount of mutations can happen if run in conjunction with `--transcriptfilter`. While I consider running the TMB calculation on preselected transcripts to be "better practice", I do not have a "known ground truth sample" to really test which combination of parameters would be the best.

2025-02-05 18:11 UTC, feiloo commented on bin/create_vembrane_fields.py
> +                'for_each_sample(lambda sample: f"allele_fraction[{sample}")'
missing ']'

2025-02-05 18:33 UTC, feiloo commented on bin/process_bedfiles.py
> +### Import dependencies
tip: skip adding comments that state the obvious

2025-02-05 18:33 UTC, feiloo commented on bin/process_bedfiles.py
> +### Define argument parser
tip: skip adding comments that state the obvious

2025-02-05 18:36 UTC, feiloo commented on bin/process_bedfiles.py
> +    header_test = any(
simplify all conditions with 'if not all([cond1, cond2, ...])'

2025-03-05 21:15 UTC, sci-kai requested changes
Hey, thanks for doing all the nice reworking of the TMB module and sorry for the late review.
I have one bigger change request for the consequence filter: 
1. Not filter at all when disabling the filter. Currently we use a whitelist in `assets` for consequences to keep when the filter is disabled. I suggest to just not do anything in the script when the filter is set to `null` to avoid potential error sources here.
2. Supply whitelist of consequence terms as comma-separated within a nextflow parameter rather than a separate file. See also the parameter `annotation_fields` as example.

Also, I found one bug with the filtering rates and one possible bug with allele fraction and coverage filter in multi-sample VCF files. The rest are smaller remarks.

Thanks a lot for implementing this and your continued work for the pipeline!

2025-03-10 14:02 UTC, biolancer commented on bin/calculate_TMB.py
> +        & (input[allele_fraction] <= higher_threshold)
The script iterates in case of multi-vcf data trough each corresponding read depth and allele frequency per sample based on the suffix, so there should actually be no impact on TMB calculation.

```
def process_multi_sample(args, suffix_list):
    ### Wrapper for multi-sample TSV
    ### Outputs each sample in the VCF/TSV as seperate file
    for suffix in suffix_list:
        allele_fraction = f'allele_fraction{suffix}'
        read_depth = f'read_depth{suffix}'
        output_filename = f"{str(args.file_out).strip('.txt')}_{suffix}.txt"
        output_plotname = f"{str(args.plot_out).strip('.png')}_{suffix}.png"
        TMB_df, filtering_rates_total = preprocess_vembraneout(
            args.file_in, allele_fraction, read_depth, args.filter_muttype, args.population_db, args.filter_consequence, args.csq_values
        )
        process_data(args, TMB_df, filtering_rates_total, args.prefilter_region, args.bedfile, allele_fraction, read_depth, output_filename, output_plotname)
```

Please correct me if I'm wrong.

2025-03-11 10:23 UTC, sci-kai commented on bin/calculate_TMB.py
> +        & (input[allele_fraction] <= higher_threshold)
You are right, it does not affect the final TMB numbers, I checked that in my test cases.
This is due to the AF/DP filter that also filters out NA entries of multi-sample vcfs.
We should emphasize in the documentation that NA values in AF/DP are also filtered by those filters.

2025-03-11 15:24 UTC, sci-kai approved these changes
LGTM! Nice work, thanks!

2025-05-20 12:17 UTC, merged